using System.Linq;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Content.Client.Lobby.UI.ProfileEditorControls;
using Content.Shared.Clothing;
using Content.Shared.Roles;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Direction = Robust.Shared.Maths.Direction;
using Robust.Client.Utility;
using Robust.Client.UserInterface;
using Robust.Shared.Map;
using Content.Shared.Dataset;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Random.Helpers;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutWindow : FancyWindow
{
    public event Action<string>? OnNameChanged;
    public event Action<JobPrototype, RoleLoadoutPrototype>? OnRoleSelected;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    private List<LoadoutGroupContainer> _groups = new();
    private readonly Dictionary<ProtoId<LoadoutGroupPrototype>, LoadoutGroupContainer> _groupContainers = new();
    private readonly Dictionary<ProtoId<LoadoutGroupPrototype>, LoadoutSlotButton> _slotButtons = new();
    private readonly Dictionary<ProtoId<LoadoutGroupPrototype>, LoadoutSlotKind> _slotKinds = new();
    private readonly List<ProtoId<LoadoutGroupPrototype>> _groupOrder = new();
    private readonly RoleLoadout _loadout;
    private readonly IDependencyCollection _collection;
    private readonly JobPrototype? _jobOverride;
    private readonly LoadoutWindowState? _initialState;
    private ProtoId<LoadoutGroupPrototype>? _selectedGroup;
    private Direction _previewRotation = Direction.North;

    public HumanoidCharacterProfile Profile;

    // CCvar.
    private int _maxLoadoutNameLength;

    public LoadoutWindow(
        HumanoidCharacterProfile profile,
        RoleLoadout loadout,
        RoleLoadoutPrototype proto,
        JobPrototype? jobOverride,
        ICommonSession session,
        IDependencyCollection collection,
        LoadoutWindowState? initialState = null)
    {
        _loadout = loadout;
        _collection = collection;
        _jobOverride = jobOverride;
        _initialState = initialState;
        RobustXamlLoader.Load(this);
        LoadoutGroupsContainer.ShowTabs = false;
        Profile = profile;
        var protoManager = collection.Resolve<IPrototypeManager>();
        var configManager = collection.Resolve<IConfigurationManager>();

        _maxLoadoutNameLength = configManager.GetCVar(CCVars.MaxLoadoutNameLength);
        ReloadPreview();
        _previewRotation = initialState?.PreviewRotation ?? Direction.North;
        SetPreviewRotation(_previewRotation);
        PopulateRolesList(protoManager, collection);
        RoleNameEdit.IsValid = text => text.Length <= _maxLoadoutNameLength;

        // Hide if we can't edit the name.
        if (!proto.CanCustomizeName)
        {
            RoleNameBox.Visible = false;
        }
        else
        {
            var name = loadout.EntityName;

            LoadoutNameLabel.Text = proto.NameDataset == null ?
                Loc.GetString("loadout-name-edit-label") :
                Loc.GetString("loadout-name-edit-label-dataset");

            RoleNameEdit.ToolTip = Loc.GetString(
                "loadout-name-edit-tooltip",
                ("max", _maxLoadoutNameLength));
            RoleNameEdit.Text = name ?? string.Empty;
            RoleNameEdit.OnTextChanged += args => OnNameChanged?.Invoke(args.Text);
        }

        // Hide if no groups
        if (proto.Groups.Count == 0)
        {
            LoadoutGroupsContainer.Visible = false;
            SetSize = Vector2.Zero;
        }
        else
        {
            foreach (var group in proto.Groups)
            {
                if (!protoManager.Resolve(group, out var groupProto))
                    continue;

                if (groupProto.Hidden)
                    continue;

                var container = new LoadoutGroupContainer(profile, loadout, groupProto, session, collection);
                LoadoutGroupsContainer.AddTab(container, Loc.GetString(groupProto.Name));
                _groups.Add(container);
                _groupContainers[group] = container;
                _groupOrder.Add(group);

                container.OnLoadoutPressed += args =>
                {
                    OnLoadoutPressed?.Invoke(group, args);
                };

                container.OnLoadoutUnpressed += args =>
                {
                    OnLoadoutUnpressed?.Invoke(group, args);
                };
            }

            LoadoutGroupsContainer.OnTabChanged += index =>
            {
                if (index < 0 || index >= _groupOrder.Count)
                    return;

                _selectedGroup = _groupOrder[index];
                UpdateSlotButtonPressedStates();
            };

            PopulateSlotButtons(loadout, protoManager);
            SelectLoadoutGroup(initialState?.SelectedGroup);
        }

        CharacterRotateLeft.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCw();
            SetPreviewRotation(_previewRotation);
        };

        CharacterRotateRight.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCcw();
            SetPreviewRotation(_previewRotation);
        };

    }

    protected override void Opened()
    {
        base.Opened();

        if (_initialState == null)
            return;

        RolesScroll.VScroll = _initialState.RolesScroll;
        RolesScroll.VScrollTarget = _initialState.RolesScroll;
        SelectLoadoutGroup(_initialState.SelectedGroup);
    }

    public LoadoutWindowState GetState()
    {
        return new LoadoutWindowState(
            RolesScroll.VScrollTarget,
            _previewRotation,
            _selectedGroup);
    }

    private void PopulateRolesList(IPrototypeManager protoManager, IDependencyCollection collection)
    {
        RolesList.RemoveAllChildren();

        var sprite = collection.Resolve<IEntityManager>().System<SpriteSystem>();
        var firstCategory = true;
        var departments = protoManager.EnumeratePrototypes<DepartmentPrototype>()
            .Where(department => !department.EditorHidden)
            .ToList();

        departments.Sort(DepartmentUIComparer.Instance);

        foreach (var department in departments)
        {
            var jobs = department.Roles
                .Select(jobId => protoManager.Index(jobId))
                .Where(job => job.SetPreference)
                .ToArray();

            Array.Sort(jobs, JobUIComparer.Instance);

            if (jobs.Length == 0)
                continue;

            if (!firstCategory)
            {
                RolesList.AddChild(new Control { MinSize = new Vector2(0, 8) });
            }

            firstCategory = false;
            RolesList.AddChild(CreateDepartmentHeader(department));

            foreach (var job in jobs)
            {
                var hasLoadout = protoManager.TryIndex<RoleLoadoutPrototype>(
                    LoadoutSystem.GetJobPrototype(job.ID),
                    out var roleLoadoutProto);

                RolesList.AddChild(CreateRoleButton(job, roleLoadoutProto, hasLoadout, sprite, protoManager));
            }
        }
    }

    private static Control CreateDepartmentHeader(DepartmentPrototype department)
    {
        return new Label
        {
            Margin = new Thickness(0, 4, 0, 2),
            Text = Loc.GetString(department.Name),
            ClipText = true,
        };
    }

    private Button CreateRoleButton(
        JobPrototype job,
        RoleLoadoutPrototype? roleLoadoutProto,
        bool hasLoadout,
        SpriteSystem sprite,
        IPrototypeManager protoManager)
    {
        var button = new Button
        {
            HorizontalExpand = true,
            MinSize = new Vector2(250, 34),
            Margin = new Thickness(0, 2, 0, 0),
            ToolTip = job.LocalizedDescription,
            Disabled = !hasLoadout,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            MouseFilter = MouseFilterMode.Ignore,
        };

        if (protoManager.Resolve(job.Icon, out var jobIcon))
        {
            row.AddChild(new TextureRect
            {
                Texture = sprite.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 6, 0),
                MouseFilter = MouseFilterMode.Ignore,
            });
        }

        row.AddChild(new Label
        {
            Text = job.ID == _jobOverride?.ID
                ? $"> {job.LocalizedName}"
                : job.LocalizedName,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
            ClipText = true,
            MouseFilter = MouseFilterMode.Ignore,
        });

        button.AddChild(row);

        if (hasLoadout && roleLoadoutProto != null)
        {
            button.OnPressed += _ => OnRoleSelected?.Invoke(job, roleLoadoutProto);
        }

        return button;
    }

    public void RefreshLoadouts(RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        foreach (var group in _groups)
        {
            group.RefreshLoadouts(Profile, loadout, session, collection);
        }

        RefreshSlotButtons(loadout, collection.Resolve<IPrototypeManager>());
    }

    public void SetProfile(HumanoidCharacterProfile profile)
    {
        Profile = profile;
        ReloadPreview();
    }

    public void ReloadPreview()
    {
        if (Profile == null)
            return;

        CharacterPreview.LoadPreview(Profile, _jobOverride, true);
        SetPreviewRotation(_previewRotation);
    }

    private void SetPreviewRotation(Direction direction)
    {
        CharacterPreview.OverrideDirection = (Direction)((int)direction % 4 * 2);
    }

    private void PopulateSlotButtons(RoleLoadout loadout, IPrototypeManager protoManager)
    {
        ClearSlotPlaceholders();
        _slotButtons.Clear();
        _slotKinds.Clear();

        var usedSlots = new HashSet<LoadoutSlotKind>();

        foreach (var groupId in _groupOrder)
        {
            if (!protoManager.Resolve(groupId, out var groupProto))
                continue;

            var slotKind = GetSlotKind(groupProto.ID);
            if (slotKind == LoadoutSlotKind.Hidden || !usedSlots.Add(slotKind))
                continue;

            var button = new LoadoutSlotButton(groupId, groupProto, _collection);
            button.OnPressed += _ => SelectLoadoutGroup(groupId);
            GetSlotPlaceholder(slotKind).AddChild(button);
            _slotButtons[groupId] = button;
            _slotKinds[groupId] = slotKind;
        }

        RefreshSlotButtons(loadout, protoManager);
        UpdateSlotButtonPressedStates();
    }

    private void RefreshSlotButtons(RoleLoadout loadout, IPrototypeManager protoManager)
    {
        foreach (var (groupId, button) in _slotButtons)
        {
            if (!protoManager.Resolve(groupId, out var groupProto))
                continue;

            button.SetLoadout(GetSingleSelectedLoadout(loadout, groupProto, protoManager));
        }
    }

    private LoadoutPrototype? GetSingleSelectedLoadout(RoleLoadout loadout, LoadoutGroupPrototype groupProto, IPrototypeManager protoManager)
    {
        if (groupProto.MaxLimit != 1)
            return null;

        if (!loadout.SelectedLoadouts.TryGetValue(groupProto.ID, out var selected) || selected.Count != 1)
            return null;

        return protoManager.Resolve(selected[0].Prototype, out var loadoutProto)
            ? loadoutProto
            : null;
    }

    private void SelectLoadoutGroup(ProtoId<LoadoutGroupPrototype>? groupId)
    {
        if (groupId == null || !_groupContainers.TryGetValue(groupId.Value, out var selected))
        {
            groupId = _groupOrder.FirstOrDefault();
            if (groupId == null || !_groupContainers.TryGetValue(groupId.Value, out selected))
                return;
        }

        foreach (var (id, container) in _groupContainers)
        {
            container.Visible = id == groupId.Value;
        }

        var index = _groupOrder.IndexOf(groupId.Value);
        if (index >= 0 && index != LoadoutGroupsContainer.CurrentTab)
            LoadoutGroupsContainer.SelectTab(index);

        _selectedGroup = groupId.Value;
        UpdateSlotButtonPressedStates();
    }

    private void UpdateSlotButtonPressedStates()
    {
        foreach (var (groupId, button) in _slotButtons)
        {
            button.Pressed = _selectedGroup == groupId;
        }
    }

    private void ClearSlotPlaceholders()
    {
        GlassesSlot.RemoveAllChildren();
        HeadSlot.RemoveAllChildren();
        MaskSlot.RemoveAllChildren();
        EarsSlot.RemoveAllChildren();
        NeckSlot.RemoveAllChildren();
        GlovesSlot.RemoveAllChildren();
        ShoesSlot.RemoveAllChildren();
        BackpackSlot.RemoveAllChildren();
        OuterClothingSlot.RemoveAllChildren();
        JumpsuitSlot.RemoveAllChildren();
        CapeSlot.RemoveAllChildren();
        BeltSlot.RemoveAllChildren();
        BackSlot.RemoveAllChildren();
        PdaSlot.RemoveAllChildren();
        TrinketsSlot.RemoveAllChildren();
    }

    private Control GetSlotPlaceholder(LoadoutSlotKind slotKind)
    {
        return slotKind switch
        {
            LoadoutSlotKind.Glasses => GlassesSlot,
            LoadoutSlotKind.Head => HeadSlot,
            LoadoutSlotKind.Mask => MaskSlot,
            LoadoutSlotKind.Ears => EarsSlot,
            LoadoutSlotKind.Neck => NeckSlot,
            LoadoutSlotKind.Gloves => GlovesSlot,
            LoadoutSlotKind.Shoes => ShoesSlot,
            LoadoutSlotKind.Backpack => BackpackSlot,
            LoadoutSlotKind.OuterClothing => OuterClothingSlot,
            LoadoutSlotKind.Jumpsuit => JumpsuitSlot,
            LoadoutSlotKind.Cape => CapeSlot,
            LoadoutSlotKind.Belt => BeltSlot,
            LoadoutSlotKind.Back => BackSlot,
            LoadoutSlotKind.Pda => PdaSlot,
            LoadoutSlotKind.Trinkets => TrinketsSlot,
            _ => throw new ArgumentOutOfRangeException(nameof(slotKind), slotKind, "Loadout slot has no placeholder."),
        };
    }

    private static LoadoutSlotKind GetSlotKind(string groupId)
    {
        var id = groupId.ToLowerInvariant();

        if (id.Contains("survival") ||
            id.Contains("tank") ||
            id.Contains("breath") ||
            id.Contains("cash"))
        {
            return LoadoutSlotKind.Hidden;
        }

        if (id.Contains("suitstorage") || id.Contains("siutstorage"))
            return LoadoutSlotKind.Back;

        if (id.Contains("glasses") || id.Contains("eyes"))
            return LoadoutSlotKind.Glasses;

        if (id.Contains("headset") || id.Contains("ears"))
            return LoadoutSlotKind.Ears;

        if (id.Contains("mask") || id.Contains("face"))
            return LoadoutSlotKind.Mask;

        if (id.Contains("head"))
            return LoadoutSlotKind.Head;

        if (id.Contains("gloves"))
            return LoadoutSlotKind.Gloves;

        if (id.Contains("shoes"))
            return LoadoutSlotKind.Shoes;

        if (id.Contains("backpack"))
            return LoadoutSlotKind.Backpack;

        if (id.Contains("outerclothing") || id.Contains("outer"))
            return LoadoutSlotKind.OuterClothing;

        if (id.Contains("jumpsuit"))
            return LoadoutSlotKind.Jumpsuit;

        if (id.Contains("sponsor") || id.Contains("cloak") || id.Contains("cape"))
            return LoadoutSlotKind.Cape;

        if (id.Contains("belt"))
            return LoadoutSlotKind.Belt;

        if (id.Contains("pda") || id.Contains("id"))
            return LoadoutSlotKind.Pda;

        if (id.Contains("trinket"))
            return LoadoutSlotKind.Trinkets;

        if (id.Contains("neck"))
            return LoadoutSlotKind.Neck;

        if (id.EndsWith("back"))
            return LoadoutSlotKind.Back;

        return LoadoutSlotKind.Hidden;
    }
}

public sealed record LoadoutWindowState(
    float RolesScroll,
    Direction PreviewRotation,
    ProtoId<LoadoutGroupPrototype>? SelectedGroup);

internal enum LoadoutSlotKind
{
    Hidden,
    Glasses,
    Head,
    Mask,
    Ears,
    Neck,
    Gloves,
    Shoes,
    Backpack,
    OuterClothing,
    Jumpsuit,
    Cape,
    Belt,
    Back,
    Pda,
    Trinkets,
}

internal sealed class LoadoutSlotButton : Button
{
    private readonly IEntityManager _entManager;
    private readonly LoadoutSystem _loadoutSystem;
    private readonly SpriteView _sprite;
    private EntityUid? _entity;

    public LoadoutSlotButton(ProtoId<LoadoutGroupPrototype> groupId, LoadoutGroupPrototype groupProto, IDependencyCollection collection)
    {
        _entManager = collection.Resolve<IEntityManager>();
        _loadoutSystem = _entManager.System<LoadoutSystem>();

        ToggleMode = true;
        MinSize = new Vector2(84, 84);
        HorizontalExpand = true;
        VerticalExpand = true;
        ToolTip = Loc.GetString(groupProto.Name);

        _sprite = new SpriteView
        {
            Scale = new Vector2(3.5f, 3.5f),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MouseFilter = MouseFilterMode.Ignore,
        };

        AddChild(_sprite);
    }

    public void SetLoadout(LoadoutPrototype? loadout)
    {
        ClearEntity();

        if (loadout == null)
            return;

        var entityProto = loadout.DummyEntity ?? _loadoutSystem.GetFirstOrNull(loadout);
        if (entityProto == null)
            return;

        _entity = _entManager.SpawnEntity(entityProto, MapCoordinates.Nullspace);
        _sprite.SetEntity(_entity);
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
            ClearEntity();
    }

    private void ClearEntity()
    {
        if (_entity == null)
            return;

        _entManager.DeleteEntity(_entity);
        _entity = null;
        _sprite.SetEntity(null);
    }
}
